version: '3'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

  postgres:
    image: "postgres:13.5"
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "api_users"
      POSTGRES_USER: "dbuser"
      POSTGRES_PASSWORD: "1122"
